# Generated by Django 4.2.11 on 2024-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
