# Generated by Django 5.0.4 on 2024-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
